# Generated by Django 2.2 on 2020-05-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastpass_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordconverter',
            name='category',
            field=models.CharField(choices=[('AES Cryptography', 'AES Cryptography'), ('RSA Cipher', 'RSA Cipher')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='passwordconverter',
            name='plainText',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='passwordconverter',
            name='individualPassword',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
