# Generated by Django 2.2 on 2020-05-29 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lastpass_api', '0003_auto_20200529_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastPassUserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_website', models.CharField(blank=True, max_length=225, null=True)),
                ('url_of_website', models.URLField(blank=True, max_length=255, null=True)),
                ('username_for_website', models.CharField(max_length=225, null=True)),
                ('password_for_website', models.CharField(max_length=225, null=True)),
                ('notes', models.TextField(blank=True)),
                ('ogUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PasswordConverter',
        ),
    ]
