# Generated by Django 2.2 on 2020-09-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastpass_api', '0005_lp_dummydata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LP_DummyData',
        ),
        migrations.AlterField(
            model_name='lastpassuserdata',
            name='password_for_website',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lastpassuserdata',
            name='username_for_website',
            field=models.TextField(blank=True, max_length=225, null=True),
        ),
    ]
