<div class="page-wrapper bg-gra-01 p-t-180 p-b-100 font-poppins">
<div class="wrapper wrapper--w780">
<div class="card card-3">
<div class="card-heading"></div>
<div class="card-body">
<h2 class="title">Registration Info</h2>
<form method="POST">
<div class="input-group">
<input class="input--style-3" type="text" placeholder="Name" name="name">
</div>
<div class="input-group">
<input class="input--style-3 js-datepicker" type="text" placeholder="Birthdate" name="birthday">
<i class="zmdi zmdi-calendar-note input-icon js-btn-calendar"></i>
</div>
<div class="input-group">
<div class="rs-select2 js-select-simple select--no-search">
<select name="gender" tabindex="-1" class="select2-hidden-accessible" aria-hidden="true">
<option disabled="disabled" selected="selected">Gender</option>
<option>Male</option>
<option>Female</option>
<option>Other</option>
</select><span class="select2 select2-container select2-container--default" dir="ltr" style="width: 69px;"><span class="selection"><span class="select2-selection select2-selection--single" role="combobox" aria-haspopup="true" aria-expanded="false" tabindex="0" aria-labelledby="select2-gender-7x-container"><span class="select2-selection__rendered" id="select2-gender-7x-container" title="Gender">Gender</span><span class="select2-selection__arrow" role="presentation"><b role="presentation"></b></span></span></span><span class="dropdown-wrapper" aria-hidden="true"></span></span>
<div class="select-dropdown"></div>
</div>
</div>
<div class="input-group">
<input class="input--style-3" type="email" placeholder="Email" name="email">
</div>
<div class="input-group">
<input class="input--style-3" type="text" placeholder="Phone" name="phone">
</div>
<div class="p-t-10">
<button class="btn btn--pill btn--green" type="submit">Submit</button>
</div>
</form>
</div>
</div>
</div>
</div>