
###sign up
POST http://127.0.0.1:8000/api/login/ HTTP/1.1
Content-Type: application/json

{
    "username":"chinmaydali395@gmail.com",
    "password":"test@1234"
}

### Create operation
POST http://127.0.0.1:8000/lastpass_api/feed_clone/ HTTP/1.1
Content-Type: application/json
Authorization: Token 5b01d4b70a5f82081ba49ce3ed1b6168d8bf1052

{
    "name_of_website": "GitHub",
    "url_of_website": "https://github.com/",
    "username_for_website": "Chinmay-395",
    "password_for_website": "test",
    "notes": "learning git actions"
}
###Retrieving all the entries
GET http://127.0.0.1:8000/lastpass_api/feed_clone/ HTTP/1.1
Content-Type: application/json
Authorization: Token 5b01d4b70a5f82081ba49ce3ed1b6168d8bf1052


### Retrieving a particular entry
## getting the first entry
GET http://127.0.0.1:8000/lastpass_api/feed_clone/1/ HTTP/1.1
Content-Type: application/json
Authorization: Token 5b01d4b70a5f82081ba49ce3ed1b6168d8bf1052

# {
#     "name_of_website": "GitHub",
#     "url_of_website": "https://github.com/",
#     "username_for_website": "Chinmay-395",
#     "password_for_website": "test",
#     "notes": "learning git actions"
# }

###Update the entry
PATCH http://127.0.0.1:8000/lastpass_api/feed_clone/1/ HTTP/1.1
Content-Type: application/json
Authorization: Token 5b01d4b70a5f82081ba49ce3ed1b6168d8bf1052

{
    "name_of_website": "Yuho",
    "url_of_website": "https://github.com/",
    "username_for_website": "Chinmay-395",
    "password_for_website": "test",
    "notes": ""
}